apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fincore.fullname" . }}-config
  labels:
    {{- include "fincore.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.backend.env.APP_ENV | quote }}
  LOG_FORMAT: {{ .Values.backend.env.LOG_FORMAT | quote }}
  LOG_LEVEL_FINCORE: {{ .Values.backend.env.LOG_LEVEL_FINCORE | quote }}
  DB_PORT: {{ .Values.backend.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.backend.env.DB_NAME | quote }}
  DB_POOL_MAX: {{ .Values.backend.env.DB_POOL_MAX | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.env.SPRING_PROFILES_ACTIVE | quote }}
