apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fincore.fullname" . }}-network-policy
  labels:
    {{- include "fincore.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.web.service.port }}
        - protocol: TCP
          port: {{ .Values.backend.service.port }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: web
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.port }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: {{ .Values.database.port }}
