apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fincore-backend-hpa
  namespace: fincore
  labels:
    app.kubernetes.io/name: fincore-backend-hpa
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fincore-360
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fincore-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
