apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fincore

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - hpa.yaml
  - ingress.yaml
  - migration-job.yaml
  - network-policy.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: fincore-360
