apiVersion: v1
kind: Namespace
metadata:
  name: fincore
  labels:
    name: fincore
    app.kubernetes.io/part-of: fincore-360
    # Pod Security Standards — Enforce Restricted Profile
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
