apiVersion: v1
kind: Service
metadata:
  name: fincore-web
  namespace: fincore
  labels:
    app.kubernetes.io/name: fincore-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: fincore-360
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: fincore-web
